### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by sauravhub** [SaifurRahmanMohsin/RESTful-Plugin#13]
I'm new in october cms, not understand documentation clearly,. Is there any video tutorial for this API?
it will very thankful if someone help me.

Thanks

**Comment by SaifurRahmanMohsin** [comment]
No, there is no video tutorial. The plugin isn’t a drag and drop style plugin and it’s mainly made for developers. If you couldn’t understand it via the documentation then I think this won’t help you much. I do plan to make a drag and drop style version of this plugin in the future that any non-developer can use as well but that will take a long time.
