### ISSUE TITLE
trying to insert (store) a new resource via the api

### ISSUE THREAD

**Issue by mpenna** [SaifurRahmanMohsin/RESTful-Plugin#3]
I was able to get a simple but functioning REST API going by following all the tips and pointers available at this October's forum thread (http://octobercms.com/forum/post/how-to-building-restful-api), even with JWT authentication added to the whole thing, but now that I'm trying to insert a new resource via the API, it is not working. It's a simple "movies" resource with an auto-incrementing ID along with a couple other very simple columns, but upon issuing a properly authenticated POST request, this is what I get in return: 

"SQLSTATE[HY000]: General error: 1364 Field 'title' doesn't have a default value (SQL: insert into `watchlearn_movies_movies` () values ())"

And here is the request: 

POST /api/v1/movies HTTP/1.1
Host: tests029.app
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL3Rlc3RzMDI5LmFwcFwvYXBpXC9hdXRoZW50aWNhdGUiLCJpYXQiOjE0NzkzMjQ4OTMsImV4cCI6MTQ3OTMyODQ5MywibmJmIjoxNDc5MzI0ODkzLCJqdGkiOiI4ZWZlZmExYmZkNGIzM2FiYjQ4MjJkMTlmZjY5NzAwZiJ9.8tJwehbN9cKRWCX_v-s1bvyvzHLqNFCMj7wVgvOhV9g
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 084fc61e-0f96-3d43-c6af-7d10330b5534

{
	"title": "Movie Inserted Via REST",
	"description": "This movie has been inserted via a REST request",
	"year": 2016,
	"slug": "movie-inserted-via-rest"
}

Oddly, all fields and their corresponding values are being ignored when it comes to building the SQL statement. 

Maybe you can make something out of this.

**Comment by mpenna** [comment]
Apparently, making the following edit inside RestController's store() method fixes the problem:

    public function store()
    {
        //$data = post();
        $data = Request::all();

        ...
    }

But I'm not sure if this is the proper way to fix this.

**Comment by SaifurRahmanMohsin** [comment]
Request::all() too can be used. Not a problem. I’m not sure why yours is failing.

I can help you with this but it would take a while. I’m presently engrossed with some project work.
Here’s some code from the old project where I made this work.
In routes.php
```
    // Routes that come with authorized token
    Route::group(['before' => 'jwt-auth'], function()
    {
      Route::get('me', function () {
          $user = LoginUtils::getUserFromToken();
          return Response::json($user);
        });
    });
```

This was for Facebook login.

In Plugin.php
```
    public function register()
    {
        $alias = AliasLoader::getInstance();
        $alias->alias('JWTAuth', 'Tymon\JWTAuth\Facades\JWTAuth');

        App::register('Tymon\JWTAuth\Providers\JWTAuthServiceProvider');
        App::register(‘Mohsin\FacebookLogin\Providers\JWTServiceProvider');
    }
```
And JWTServiceProvider.php had:
```

class JWTServiceProvider extends ServiceProvider
{
    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->registerMiddleware('jwt.auth', 'Tymon\JWTAuth\Middleware\GetUserFromToken');
        $this->registerMiddleware('jwt.refresh', 'Tymon\JWTAuth\Middleware\RefreshToken');
    }

    /**
     * Helper method to quickly setup middleware.
     *
     * @param string $alias
     * @param string $class
     */
    protected function registerMiddleware($alias, $class)
    {
        $this->app['router']->middleware($alias, $class);
    }
}
```

I hope yours has something of this sort. If so it should work fine. If you still cannot figure it out, it it possible for you to zip and email this plugin? I can take a look in any spare time and write back the solution. Upload somewhere and [email](mailto:mohsin92@me.com) it to me. Otherwise, I think it may take a while to figure out why you are facing the issue.
