### ISSUE TITLE
[Q] Access point

### ISSUE THREAD

**Issue by raisty** [SaifurRahmanMohsin/RESTful-Plugin#5]
What is the URL access point or how to setup it?
I try: http://domain.tld/api/v1 
And nothing happen - October CMS Not found 404.

**Comment by SaifurRahmanMohsin** [comment]
Please read [the documentation](http://octobercms.com/plugin/mohsin-rest#documentation). The way RESTful works is that it generates RESTful controllers from controllers that are written on other plugins. The plugin exposes a [scaffolding command](http://octobercms.com/docs/console/scaffolding) which can be run from a terminal / console. Simply CD into your OctoberCMS project and run the command to create a RESTful controller for your existing controller. So, if you have a plugin that has a **People** (for example) controller then it would be accessible like:
```
http://domain.tld/api/v1/people
```
