### ISSUE TITLE
How to create REST controller for a model extending another?

### ISSUE THREAD

**Issue by kealsera** [SaifurRahmanMohsin/RESTful-Plugin#7]
Hey!

I created a model which will be added to Rainlab.User with this code

```
UserModel::extend(function($model){
    		$model->hasOne['sloth'] = ['Rikki\Heroeslounge\Models\Sloth', 'delete' => true];
    	});
```

I guess best practice with your code would be to just create the controller manually, wouldn't it?
My model doesn't have a controller in this case, since the belonging controller is in Rainlab.Users.

**Comment by SaifurRahmanMohsin** [comment]
Yep. I haven't covered more complex use cases yet. This plugin has several features that are yet to be added until then you would have to do this manually.
