### ISSUE TITLE
Additional Parameters

### ISSUE THREAD

**Issue by kealsera** [SaifurRahmanMohsin/RESTful-Plugin#8]
I try to add more paramters for more queries, but I cannot read out of Laravels Documentation what I am doing wrong here.

This is my route.php

```
<?php

Route::group(['prefix' => 'api/v1'], function () {
    Route::resource('teams', 'Rikki\Heroeslounge\Http\Team');
    Route::resource('seasons', 'Rikki\Heroeslounge\Http\Season');
    Route::resource('divisions', 'Rikki\Heroeslounge\Http\Division');
    Route::get('maps/{enabled}','Rikki\Heroeslounge\Http\Map@getEnabled');
    Route::resource('maps', 'Rikki\Heroeslounge\Http\Map');
    Route::resource('matches', 'Rikki\Heroeslounge\Http\Match');
    Route::resource('timeline', 'Rikki\Heroeslounge\Http\Timeline');
    Route::resource('applications', 'Rikki\Heroeslounge\Http\Applications');
    
});
```

and this is my Controller:

```
<?php namespace Rikki\Heroeslounge\Http;

use Backend\Classes\Controller;
/**
 * Map Back-end Controller
 */
class Map extends Controller
{
    public $implement = [
        'Mohsin.Rest.Behaviors.RestController'
    ];

    public $restConfig = 'config_rest.yaml';

    public function getEnabled($enabled)
    {
        return 'test';
    }
}

```

However if I try to access:

../maps/1
../maps/enabled=1
../maps?enabled=1
../maps/getEnabled=1
../maps/getEnabled/1

I simply get the response

{"response":"Not Found"}
What am I doing wrong? ⭕️

**Comment by SaifurRahmanMohsin** [comment]
Hey. Sorry for the delayed response. It appears that you have not mentioned getEnabled in config_rest.yaml file under the allowed actions. Specify it like this:

```
# ===================================
#  Rest Behavior Config
# ===================================

# Allowed Rest Actions
allowedActions:
  getEnabled:

# Model Class name
modelClass: Rikki\Heroeslounge\Models\Map

```

Let me know if you have resolved this issue so that I can close it.

**Comment by kealsera** [comment]
Apprently that was the case - I named the allowed Action just 'enabled' -.-*

But how am I able to differentiate parameters?

`http://localhost:5576/api/v1/maps/1`

Would be a valid url for index based & my custom route
`Route::get('maps/{enabled}', 'Rikki\Heroeslounge\Http\Map@getEnabled');`
I'd rather have my custom route to be adressed by

`http://localhost:5576/api/v1/maps?enabled=value`

So I am even able to chain these

**Comment by SaifurRahmanMohsin** [comment]
If you want to work with URL parameters then you would have to collect the data inside the controller function i.e. inside getEnabled you use something like:

```
$data = Input::all();
$enabled = array_get($data, 'enabled');
```

Also you shouldn't mention enabled in `Route::get('maps/{enabled}', 'Rikki\Heroeslounge\Http\Map@getEnabled');` and keep it just as `Route::get('maps', 'Rikki\Heroeslounge\Http\Map@getEnabled');`

So now the route points to `http://localhost:5576/api/v1/maps` and the parameter enabled can be taken from within the target method i.e. getEnabled.

**Comment by kealsera** [comment]
That's working - thanks for your support! :)
